server:
  port: 10000
  servlet:
    context-path: /diff

spring:
  application:
    name: Diff

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://192.168.124.23:40953/db_diff?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false
    url: jdbc:mysql://127.0.0.1:3306/db_diff?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false
    username: root
    password: 12345678

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
